# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cb5448b7750f2a59b6d4385399485b41"
name = "email-marketing"
handle = "email-marketing-24"
application_url = "https://loop-referrals-rachel-substances.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-60d2e6a4.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"

[auth]
redirect_urls = [
  "https://loop-referrals-rachel-substances.trycloudflare.com/auth/callback",
  "https://loop-referrals-rachel-substances.trycloudflare.com/auth/shopify/callback",
  "https://loop-referrals-rachel-substances.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
